// IF ANYTHING BREAKS, CHECK THIS SECTION FIRST.
// IF SEARCH RESULTS DO NOT APPEAR, CHECK:
// 1) Firebase config values are correct
// 2) the element IDs in HTML match these variables
// 3) the database collection names are correct
// WAIT FOR PAGE TO LOAD
// THIS ALLOWS THE PAGE TO LOAD FIRST
document.addEventListener('DOMContentLoaded', function() {

  // GET THE 3 THINGS FROM HTML
  // OF COURSE DECLARED A VARIABLE AND ASKED THE DOCUMENT TO GET THE ELEMENT WITH THE ID'S
  const searchInput = document.getElementById('search-input'); 
  const resultsDiv = document.getElementById('search-results');
  const searchContainer = document.getElementById('search-container');

  // IF SEARCH DOES NOT WORK, CHECK THIS FIREBASE CONFIG.
  // IF THE KEYS ARE WRONG OR THE PROJECT IS DIFFERENT, THE QUERY WILL FAIL.
  // CONNECT FIREBASE - REPLACE WITH YOUR KEYS
  // THIS CONNECTS THE JAVASCRIPT TO FIREBASE SO WE CAN SEARCH THE DATABASE 
  // NOTE: THIS IS A FIREBASE CONGIGURATION OBJECT GENERATED BY FIRE BASE. YOU NEED TO REPLACE THE VALUES WITH YOUR OWN FIREBASE PROJECT'S CONFIGURATION.
const firebaseConfig = {
  apiKey: "AIzaSyD2dnVrNfzx8ktUT4s2ocJ5Q2-VhJR66A4",
  authDomain: "boomer-431e6.firebaseapp.com",
  projectId: "boomer-431e6",
  storageBucket: "boomer-431e6.firebasestorage.app",
  messagingSenderId: "481343133195",
  appId: "1:481343133195:web:ef20f718dd4ae4e574990e"
};

// THIS ACTIVATES THE FIREBASE
  if (!firebase.apps || !firebase.apps.length) {
    firebase.initializeApp(firebaseConfig);
  }
  const db = window.db || firebase.firestore();
  window.db = db;

  // WHEN USER TYPES
  // THIS HELPS THE JAVASCRIPT TO LISTEN TO THE EVENT INPUT WHICH MEANS TYPING...THEN GAVE IT A FUNCTION/WHAT TO DO NEXT
  searchInput.addEventListener('input', function(e) {

    // THIS CHANGES IT TO LOWER CASE BEHIND THE SCENE SO THE SEARCHBAR IS NOT LIMITED TO SENTENCE CASE
    const term = e.target.value.toLowerCase();
    
    // THIS SAYS IF THE LETTERS TYPED IS LESS THAN 2 LETTERS DON'T DISPLAY ANYTHING
    if (term.length < 2) {
      resultsDiv.style.display = 'none';
      return;
    }
    
    // THIS ALLOWS THE SEARCH RESULT DISPLAY IN BLOCK
    resultsDiv.style.display = 'block';

    // THIS DISPLAYS SEARCHING ON THE SCREEN
    resultsDiv.innerHTML = 'Searching...';
    
    // IF SEARCH RETURNS NOTHING, CHECK THIS QUERY.
    // IF THE COLLECTION NAME OR FIELD NAME IS WRONG, THE DATABASE WILL NOT RETURN RESULTS.
    // SEARCH FIREBASE
    // this tell the database to go to users table/folder then look at the username column where 
    // the username is greater than or equal to the term/letter typed in the search bar, limit the results to 3 and get the data
    db.collection('users').where('username', '>=', term).where('username', '<=', term + '\uf8ff').limit(3).get()

    // snapshot: a box containing all the users with the name
    // then give me all the name of the users we found in a searchbox
    .then(snapshot => {

      // Create an empty box to store HTML code, We'll fill this with <div>@username</div> for each user
      let html = '';

      // Loop through every user in the box, doc = 1 single user document from firebase
      snapshot.forEach(doc => {
        const user = doc.data();  // doc.data() = "Open this user and give me their data as a normal JS object So now user.username, user.profilePic etc will work
        
        // add this user's html to the big html box
        html += `<div style="padding:10px; cursor:pointer" onclick="window.location='/profile/${user.username}'">👤 ${user.username}</div>`;
      });

      // SEARCH POSTS TOO
      // SAME PATTERN WITH THE ONE ABOVE
      return db.collection('posts').where('title', '>=', term).where('title', '<=', term + '\uf8ff').limit(3).get()
      .then(postSnapshot => {
        postSnapshot.forEach(doc => {
          const post = doc.data();
          html += `<div style="padding:10px; border-top:1px solid #eee" onclick="window.location='/post/${doc.id}'">📄 ${post.title}</div>`;
        });

        // else if the name doest exist then display the result of no users found in html
        resultsDiv.innerHTML = html || 'No users or posts found';
      });

    })

    // if there is an error then display the error in the console
    .catch(err => {
      resultsDiv.innerHTML = 'Error: Check Firebase Rules';
      console.log(err);
    });
  });

  // CLOSE WHEN CLICK OUTSIDE
  // listen to an event called click the perform the following function of if the search container is not clicked the dont display anything or rather remove the search box result
  document.addEventListener('click', function(event) {
    if (!searchContainer.contains(event.target)) {
      resultsDiv.style.display = 'none';
    }
  });

});

// db.collection('users') = Go to the "Users" menu
// .where('username', '>=', term) = "I want dishes that start with 'ad'"
// .limit(3) = "Only bring me 3 dishes"
// .get() = "Waiter, bring the food"
// .then(snapshot) = "When food arrives..."
// snapshot.forEach = "For each plate of food..."
// doc.data() = "Unwrap the plate"

// KEY THING TO REMEMBER:This pattern is the same for EVERYTHING in Firebase:
// db.collection('TABLE').where('COLUMN', 'CONDITION', 'VALUE').get()Want to search posts next? Just change 2 words:
// db.collection('posts').where('title', '>=', term).get()Does this make sense now bro? 
// Which part still feels like magic to you?